kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: install
  image: node:lts
  volumes:
  - name: cache
    path: /node_modules
  commands:
    - yarn install
- name: test
  image: node:lts
  volumes:
  - name: cache
    path: /node_modules
  commands:
    - npm test

volumes:
- name: cache
  temp: {}
