version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
     - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: ./secret/config.env

  node:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../release:/usr/src/app
      - /usr/src/app/node_modules # otherwise prev volume overwrites
      - /etc/letsencrypt/live/picchietti.io/privkey.pem:/usr/src/app/secret/letsencrypt/privkey.pem
      - /etc/letsencrypt/live/picchietti.io/fullchain.pem:/usr/src/app/secret/letsencrypt/fullchain.pem
    env_file: ./secret/config.env
    depends_on:
      - mysql
    links:
      - mysql
    command: /usr/bin/supervisord
