# env vars used here are defined in ./.env

version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: ./src/secret/config.env

  mongo:
    image: mongo:latest
    ports:
      - "${HOST_MONGO_PORT}:27017"
    volumes:
      - ./mongo/data:/data/db
    command: mongod --auth

  node:
    build: .
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules # otherwise prev volume overwrites
      - ./package.json:/usr/src/app/package.json # otherwise prev volume overwrites
    env_file: ./src/secret/config.env
    depends_on:
      - mysql
      - mongo
    links:
      - mysql
      - mongo
    command: /usr/bin/supervisord
