# env vars used here are defined in ./.env

version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "${HOST_MONGO_PORT}:27017"
    volumes:
      - ./mongo/data:/data/db
      - "./src/secret/${SSL_PEM_KEY_FILE}:/ssl/${SSL_PEM_KEY_FILE}"
      - ./src/secret/rootCA.pem:/ssl/rootCA.pem
    command: mongod --auth --sslMode requireSSL -sslPEMKeyFile "/ssl/${SSL_PEM_KEY_FILE}" --sslCAFile /ssl/rootCA.pem

  node:
    build: .
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ./src:/usr/src/app/src
      - ./src/secret/letsencrypt:/etc/letsencrypt
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules # otherwise prev volume overwrites
      - ./package.json:/usr/src/app/package.json # otherwise prev volume overwrites
      - ./configs:/usr/src/app/configs # otherwise prev volume overwrites
    env_file: ./src/secret/config.env
    depends_on:
      - mongo
    links:
      - mongo
    command: /usr/bin/supervisord
