version: '2'
services:
  node:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/Desktop/release:/usr/src/app
      - /usr/src/app/picchietti.io/node_modules # otherwise prev volume overwrites
      - /etc/letsencrypt/live/picchietti.io/privkey.pem:/usr/src/app/picchietti.io/private/letsencrypt/privkey.pem
      - /etc/letsencrypt/live/picchietti.io/fullchain.pem:/usr/src/app/picchietti.io/private/letsencrypt/fullchain.pem
    depends_on:
      - mysql
    links:
      - mysql
    command: npm start

  mysql:
    image: mysql:latest
    ports:
     - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/backup/picchietti_db.sql:/docker-entrypoint-initdb.d/picchietti_db_dump.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${PICCHIETTI_MYSQL_DATABASE}
      MYSQL_USER: ${PICCHIETTI_MYSQL_USER}
      MYSQL_PASSWORD: ${PICCHIETTI_MYSQL_PASSWORD}
