# env vars used here are defined in ./.env

version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
     - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: ./build/secret/config.env

  node:
    build: .
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ./build:/usr/src/app
      - /usr/src/app/node_modules # otherwise prev volume overwrites
      - ./package.json:/usr/src/app/package.json # otherwise prev volume overwrites
      - ./build/secret/letsencrypt:/etc/letsencrypt
    env_file: ./build/secret/config.env
    depends_on:
      - mysql
    links:
      - mysql
    command: /usr/bin/supervisord
